### PR TITLE
Adding command-line interface

### PR DESCRIPTION
**Pull request by mtlynch**
Adding a CLI parser and the main module
Adding verbose logging to table equivalence checking

[Review on Reviewable](https://reviewable.io/reviews/m-lab/bigsanity/16)

### CODE REVIEW

**Comment by collina** [comment]
*[bigsanity/bigsanity.py, line 74 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nHw7P1egUX14m5ede:-K7nHw7P1egUX14m5edf:1241540870) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L74)):*
If a monthly tables had duplicates of a test_id across two tables (e.g. because of pipeline issues the test was in both February and March), would this catch that failure? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16)*

**Comment by collina** [comment]
*[bigsanity/bigsanity.py, line 130 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJDi7YmHP058tKcg2:-K7nJDi7YmHP058tKcg3:1758790673) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L130)):*
If you want to, you can hand argparse the cli data function right way in `target` https://docs.python.org/2.7/library/argparse.html#type

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16)*

**Comment by collina** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[bigsanity/bigsanity.py, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nIXcjRYr-ODUZZJT6:-K7nIXcky8A7XvcbmzaR:1086474227) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L30)):*
Can this be put somewhere else other than the main thread?

---

*[bigsanity/bigsanity.py, line 115 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nIhCf9h1BYS_3fy0r:-K7nIhCf9h1BYS_3fy0s:2115091277) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L115)):*
do we need to assign args.project and recast it as an int -- argparse should already handle the latter.

---

*[bigsanity/bigsanity.py, line 117 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJ0Z67OqQTc7lpRS6:-K7nJ0Z7BalIqNaihBGt:-987368325) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L117)):*
What's the long term objective for sys.exit(-1)?

---

*[bigsanity/bigsanity.py, line 134 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJkaj36nYtBYpcy_p:-K7nJkaj36nYtBYpcy_q:-2066022962) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L134)):*
case in point, we might want to expect argparse so we don't have to datetime => str => datetime

---

*[bigsanity/bigsanity.py, line 140 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJvwcMGhhDfudXZIK:-K7nJvwcMGhhDfudXZIL:-1361309893) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L140)):*
I'd prefer either --days or --months (or both, don't need to be exclusively called), and worse case using telescope's notation. Definitely the former though.

---

*[bigsanity/cli.py, line 33 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nKHiTF5AEN1cFZHT6:-K7nKHiTF5AEN1cFZHT7:-1685471429) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/cli.py#L33)):*
Note: haven't checked based on prior comments

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[bigsanity/bigsanity.py, line 102 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7qZjc73D5KIon5KBxl:-K7qZjc73D5KIon5KBxm:1207936111) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L102)):*
Related to Collin's comment, there are three initial checks you wanted BigSanity to monitor and a goal for the design is easy extensibility, right? Where did you plan to  be able to add new checks? 

Also it seems kind of weird to have found_error, but its only job to be inverted at return. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16)*

**Comment by mtlynch** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[bigsanity/bigsanity.py, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nIXcjRYr-ODUZZJT6:-K7qXbufnUantDXzFxAI:455614157) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L30)):*
(Assuming s/thread/module/ )

Good point. Moved it to its own module.

---

*[bigsanity/bigsanity.py, line 74 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nHw7P1egUX14m5ede:-K7qXudXRx7wbL62IFzh:-1603866476) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L74)):*
It does not. Uniqueness checks (or duplicate checks) are scheduled for M5 of BigSanity, but only on the fast tables. Uniqueness checks on the monthly tables are possible, but prohibitively slow, so I feel like they don't meet the bar, especially given that I predict monthly tables as becoming irrelevant once the fast tables are officially released.

---

*[bigsanity/bigsanity.py, line 102 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7qZjc73D5KIon5KBxl:-K7qieX4QJDbs-4w3qJl:1233556588) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L102)):*
> Related to Collin's comment, there are three initial checks you wanted BigSanity to monitor and a goal for the design is easy extensibility, right? Where did you plan to be able to add new checks?

Good question. Right now I don't have a clear plan except to encapsulate the logic of each check into its own class as much as possible. And now that you're calling this out, I'm realizing that it kind of implies that `is_sane` is a general function that can run many checks, but that kind of conflicts with the design doc, which says we'd run each type of check as a separate instance of the program. I've renamed it to `_do_cross_table_consistency_check`.

So right now I'd say that the plan is to just choose checker functions at runtime based on the command line parameters. So like if it's:

```
python bigsanity/bigsanity.py --check table_consistency --interval_months 12 --project 0
```

We'd call `_do_cross_table_consistency_check` whereas if it's:

```
python bigsanity/bigsanity.py --check duplicates --interval_months 12 --project 0
```

We call like `_do_duplicates_check`.

Something more elegant might come up as we start to get to a higher number of checks. If you see steps we can take now to make this more easily extensible in the future, I'm open to suggestions here. I do want to avoid adding complexity before we actually need it, but I also don't want to unknowingly paint us into a corner where it's going to be hard to scale the checks when we actually want to.

Sidenote: It's down to two checks since one of the checks was for fast-monthly tables which got cut.

> Also it seems kind of weird to have found_error, but its only job to be inverted at return.

Agreed, removed.

---

*[bigsanity/bigsanity.py, line 115 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nIhCf9h1BYS_3fy0r:-K7qi8AihDGcxKZX4u3B:-497468049) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L115)):*
Fixed

---

*[bigsanity/bigsanity.py, line 117 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJ0Z67OqQTc7lpRS6:-K7qYiv1-8ZZ1qDe82vF:-1246863747) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L117)):*
I saw this as useful so that it played nice with other command-line tools that check for a successful exit code, but now that you mention it, I don't have a specific plan so I think this falls into "designing into the future" and we should just cut it out until we know what exactly we want this for.

Removed (and now `_is_sane` doesn't need to return anything).

---

*[bigsanity/bigsanity.py, line 130 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJDi7YmHP058tKcg2:-K7q_lJ5nqiZesz1wHB6:-559152950) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L130)):*
Oh, neat! Much cleaner. Fixed.

---

*[bigsanity/bigsanity.py, line 134 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJkaj36nYtBYpcy_p:-K7q_sOUSBqEg2RWrs_c:-497468049) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L134)):*
Fixed

---

*[bigsanity/bigsanity.py, line 140 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7nJvwcMGhhDfudXZIK:-K7q_wZa3cU8PBDn-jIJ:1835206659) ([raw file](https://github.com/m-lab/bigsanity/blob/f677d1ef560ed08205240b3498e4e8a38d4473a2/bigsanity/bigsanity.py#L140)):*
Yeah that's way better. This felt very hacky to me and I couldn't think of a cleaner way.

---

*[bigsanity/cli.py, line 51 \[r3\]](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-K7qlr5P-Fijyc80zxTR:-K7qlr5P-Fijyc80zxTS:-1788541614) ([raw file](https://github.com/m-lab/bigsanity/blob/b028101d0024bed663ea4cc70915b696382d3148/bigsanity/cli.py#L51)):*
I don't like the redundancy here between `parse_interval_days_arg` and `parse_interval_months_arg` but I can't figure out a way around it.

I considered `functools.partial` but even that is kind of hard because the thing that varies is the keyword of `relativedelta` that we assign to, not a value that we pass.

Suggestions welcome.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16)*

**Comment by fernandalavalle** [comment]
LGTM

---

Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/16#-:-K7s3fbTZsxQccYGGxHW:676834233)*

**Pull request merged**
