### PR TITLE
Adding query generator to test table equivalence

### PR DESCRIPTION
**Pull request by mtlynch**
Adding TableEquivalenceQueryGenerator which generates sets of queries
that can be executed to test whether two tables contain equivalent data.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/bigsanity/4)

### CODE REVIEW

**Comment by mtlynch** [comment]
Development note: The [design doc](https://docs.google.com/document/d/1zxZ4xijTU7pvVMnf6aFP4Nupf-B_xmtRmpY3iTVgebY/edit) calls for checks on "new per-month" tables (e.g. legacy = 2015_12, new = 2015_12**_fast**).

I'm reconsidering whether the "new per-month" tables are useful, so I've left them out of BigSanity for now. They can easily be added back in if we decide to go forward on them. Look for a thread discussing this decision in the next couple weeks. I'll update the design doc when we make a decision.

**Comment by fernandalavalle** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-:-K7CEicwlzu7jV5WoUx7:-492975247)*

**Comment by collina** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[bigsanity/query_construct.py, line 41 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DRxDt2qYENEaMjPCX:-K7DRxDvOBbXXEZoWRag:-1224762908) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L41)):*
Should this be space or a tab, as with tables?

---

*[bigsanity/query_construct.py, line 44 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DSIP13U0Z6LvlVSy9:-K7DSIP13U0Z6LvlVSyA:1987479217) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L44)):*
Have we typically been more lax about documentation of private functions?  Perhaps we can include the args for this and the next couple since it's mostly copy and paste of (dt, datetime)

---

*[bigsanity/query_construct.py, line 116 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DUFgIozmsF73LiVaq:-K7DUFgIozmsF73LiVar:-1953356832) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L116)):*
Nice touch with human readable the comment. 

---

*[tests/test_query_construct.py, line 67 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DVv_N-kJ88C6CEi0g:-K7DVv_N-kJ88C6CEi0h:-1413153838) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/tests/test_query_construct.py#L67)):*
Queries end up in previous tables but not in the following tables? Would believe but double checking. I recall doing the math of the occurrence of this behavior, but should this be documented elsewhere other than within a unittest. All the more reason Telescope should be on the project table I suppose.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4)*

**Comment by collina** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4)*

**Comment by mtlynch** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[bigsanity/query_construct.py, line 41 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DRxDt2qYENEaMjPCX:-K7Hn29xKTmP5In6d90Z:-678373970) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L41)):*
Oh, good point. I actually switched everything to spaces because it's a pain to get tabs into the base format string.

---

*[bigsanity/query_construct.py, line 44 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DSIP13U0Z6LvlVSy9:-K7DhkP7P56gR1KecJmK:-1006266434) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L44)):*
I sometimes omit docstrings if it meets the style guide exception criteria. I think this one qualifies:

>A function must have a docstring, unless it meets all of the following criteria:

>* not externally visible
>* very short
>* obvious

https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments

I feel like when we document functions this short, we don't add much value and I get nervous any time I have to copy paste parts of docstrings because I feel like those tend to get out of sync, so I try to minimize the number of docstrings that should stay in sync.

---

*[bigsanity/query_construct.py, line 116 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DUFgIozmsF73LiVaq:-K7HIQFWuaxTO2WRaA6Y:-320855144) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/bigsanity/query_construct.py#L116)):*
Yeah I hate reading UNIX timestamps.

I'm considering making a proposal to switch all our stuff (BigSanity, Telescope, public docs) to use something like `TIMESTAMP_TO_SEC(TIMESTAMP("2013-05-01 00:00:00"))` so it's way easier to read/edit, but I haven't gotten around to verifying that it doesn't degrade query performance significantly.

---

*[tests/test_query_construct.py, line 67 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DVv_N-kJ88C6CEi0g:-K7HRO2OhoeTunYVtZiA:-452935089) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/tests/test_query_construct.py#L67)):*
Oh! Interesting. This implementation assumed that it could spill over into either (backwards or forwards), but after you said that, I wrote a script to check and it turns out it only ever spills forward:

```
SELECT
    month,
    num_rows
FROM (
    SELECT
        STRFTIME_UTC_USEC(UTC_USEC_TO_DAY(web100_log_entry.log_time * 1000000),
                          '%Y_%m') AS month,
        COUNT(*) AS num_rows
    FROM
        plx.google:m_lab.{month}.all
    WHERE
        IS_EXPLICITLY_DEFINED(web100_log_entry.log_time)
    GROUP BY
        month
    )
WHERE
    month != '{month}'
ORDER BY
    month ASC;
```

Output:

```
2009_02
	2009_03
2009_03
2009_04
	2009_05
2009_05
2009_06
2009_07
2009_08
	2009_09
2009_09
2009_10
	2009_11
2009_11
	2009_12
2009_12
	2010_01
2010_01
	2010_02
2010_02
	2010_03
2010_03
	2010_04
2010_04
	2010_05
2010_05
	2010_06
2010_06
	2010_07
2010_07
	2010_08
2010_08
	2010_09
2010_09
	2010_10
2010_10
	2010_11
2010_11
	2010_12
2010_12
	2011_01
2011_01
	2011_02
2011_02
	2011_03
2011_03
	2011_04
2011_04
	2011_05
2011_05
	2011_06
2011_06
	2011_07
2011_07
	2011_08
2011_08
	2011_09
2011_09
	2011_10
2011_10
	2011_11
2011_11
	2011_12
2011_12
	2012_01
2012_01
	2012_02
2012_02
	2012_03
2012_03
	2012_04
2012_04
	2012_05
2012_05
	2012_06
2012_06
	2012_07
2012_07
	2012_08
2012_08
	2012_09
2012_09
	2012_10
2012_10
	2012_11
2012_11
	2012_12
2012_12
	2013_01
2013_01
	2013_02
2013_02
	2013_03
2013_03
	2013_04
2013_04
	2013_05
2013_05
	2013_06
2013_06
	2013_07
2013_07
	2013_08
2013_08
	2013_09
2013_09
	2013_10
2013_10
	2013_11
2013_11
	2013_12
2013_12
	2014_01
2014_01
	2014_02
2014_02
	2014_03
2014_03
	2014_04
2014_04
	2014_05
2014_05
	2014_06
2014_06
	2014_07
2014_07
	2014_08
2014_08
	2014_09
2014_09
	2014_10
2014_10
	2014_11
2014_11
	2014_12
2014_12
	2015_01
2015_01
	2015_02
2015_02
	2015_03
2015_03
	2015_04
2015_04
	2015_05
2015_05
	2015_06
2015_06
	2015_07
2015_07
	2015_08
2015_08
	2015_09
2015_09
	2015_10
2015_10
	2015_11
2015_11
	2015_12
2015_12
	2016_01
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4)*

**Comment by mtlynch** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/test_query_construct.py, line 67 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DVv_N-kJ88C6CEi0g:-K7Hnp1mBJl6_2a4vh4Z:-948574322) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/tests/test_query_construct.py#L67)):*
Oh wait, forgot to actually fix this. Hang on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4)*

**Comment by mtlynch** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/test_query_construct.py, line 67 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/4#-K7DVv_N-kJ88C6CEi0g:-K7HqkMQcvB7-CwXYLOS:-1046666403) ([raw file](https://github.com/m-lab/bigsanity/blob/d30cdc0dc59057dcc04ee213d7a30ccdb09d2825/tests/test_query_construct.py#L67)):*
Actually, I'm now realizing this is implemented in `table_names.py`, which I see as out of scope for this PR. Mind if I do it in a subsequent bugfix PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/4)*

**Pull request merged**
