### PR TITLE
Adding a table equivalence check

### PR DESCRIPTION
**Pull request by mtlynch**
This class ties together the query checker and query executor and
translates the results of the query into a sanity check result
indicating whether the check indicated the tables or equivalent or if
they had mismatches.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/bigsanity/15)

### CODE REVIEW

**Comment by mtlynch** [comment]
Note: The checker depends on `QueryExecutor`, which is not yet checked in, but the coupling is loose enough that this can still be checked in now. But for clarity, if you'd like to peek at what the executor looks like, you can see it in:

https://github.com/m-lab/bigsanity/pull/13

**Comment by collina** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bigsanity/check_table_equivalence.py, line 127 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XhW1yJPCAp5PoBwA8:-K7XhW1yJPCAp5PoBwA9:-1732927053) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/bigsanity/check_table_equivalence.py#L127)):*
/ time_range_start/ time_range_end/

---

*[bigsanity/query_construct.py, line 169 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XhsCC-uEK1qyjU63Z:-K7XhsCC-uEK1qyjU63_:677039177) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/bigsanity/query_construct.py#L169)):*
Why do we create a new class for this? Also don't factories typically `yield`?

---

*[tests/test_check_table_equivalence.py, line 111 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XiggI3R9KhAPAfW_7:-K7XiggI3R9KhAPAfW_8:-1508630455) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/tests/test_check_table_equivalence.py#L111)):*
Can test the completeness of these lists in a unit test, or do you want to cover that with the QueryExecutor's unit tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/15)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bigsanity/check_table_equivalence.py, line 127 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XhW1yJPCAp5PoBwA8:-K7XnVezV1rzmluhwhrp:1672155332) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/bigsanity/check_table_equivalence.py#L127)):*
D'oh! Fixed. (and in all the places I copy/pasted these params)

---

*[bigsanity/query_construct.py, line 169 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XhsCC-uEK1qyjU63Z:-K7Xm3zAajYSSPY9PmIa:114003794) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/bigsanity/query_construct.py#L169)):*
This is to decouple `TableEquivalenceChecker` from `TableEquivalenceQueryGenerator`. Otherwise the checker is directly instantiating `TableEquivalenceQueryGenerator` and it's uglier to mock out when we want to test. 

Another alternative would be to take out all internal state in `TableEquivalenceQueryGenerator` and put all the parameters (project, times) in `generate_query` but that felt like very klunky syntax.

This seemed cleanest to me, but I'm open to other suggestions here.

re: `yield` I don't know that to be standard among factories in Python. Is it? I just now Googled "factory pattern in python" and there didn't seem to be many results that used `yield`.

---

*[tests/test_check_table_equivalence.py, line 111 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7XiggI3R9KhAPAfW_7:-K7XksIFbbbpO5QGu3AN:125253000) ([raw file](https://github.com/m-lab/bigsanity/blob/64685ee9d407b4c9f2847967ba679b2d3cad9d20/tests/test_check_table_equivalence.py#L111)):*
I'm not sure I understand what you mean by "completeness of these lists". Are you talking about tests that ensure that a given BigQuery query yields a given response? It's difficult for us to test that because I think that's a test on BigQuery. We can test that we give BigQuery the right query and that we correctly process what we expect its response to be. The only alternative I can think of would be to test against live BigQuery which would be a painful dependency in our test suite.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/15)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/test_check_table_equivalence.py, line 34 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7YE_T930jhDxXEWgJ6:-K7YE_T930jhDxXEWgJ7:870345625) ([raw file](https://github.com/m-lab/bigsanity/blob/83ffe9b8554a5ca4334fe0144455b59d248e4714/tests/test_check_table_equivalence.py#L34)):*
small typo. TableEquivalenceCheckerTest.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/15)*

**Comment by fernandalavalle** [comment]
one typo, but LGTM

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-:-K7YLEB0tl5y4S2M3l3j:1548916202)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/test_check_table_equivalence.py, line 34 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/15#-K7YE_T930jhDxXEWgJ6:-K7lDmWd4zVW5EBI1J4Y:511494430) ([raw file](https://github.com/m-lab/bigsanity/blob/83ffe9b8554a5ca4334fe0144455b59d248e4714/tests/test_check_table_equivalence.py#L34)):*
Good catch, fixed!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/15)*

**Pull request merged**
