### PR TITLE
Adding a QueryExecutor class to execute BigQuery queries

### PR DESCRIPTION
**Pull request by mtlynch**
Adding a wrapper around the bq utility which executes BigQuery queries
and returns the results in CSV format.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/bigsanity/13)

### CODE REVIEW

**Comment by pboothe** [comment]
*[bigsanity/query_execution.py, line 18 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7XyKIH_-8GXz4BEXgm:-K7XyKIIj_qBflSQt03b:1127097575) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L18)):*
This should either be `BqError` or the  subsequent classes should inherit from `Exception`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/13)*

**Comment by pboothe** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bigsanity/query_execution.py, line 18 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7XyKIH_-8GXz4BEXgm:-K7Xy_pKUP4hxLR_e4d2:1496394169) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L18)):*
Did not mean to resolve. Ugh.

---

*[bigsanity/query_execution.py, line 38 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y0XwjmvDrfAxw2A6B:-K7Y0Xwk0c0SNkxqZSEJ:503295864) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L38)):*
Newlines in exception messages make me worried, but maybe the query already has them, so my concern is moot?

---

*[test-requirements.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y-i3-3QAreamY0hMa:-K7Y-i30z2Yy57laLWBm:282602867) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/test-requirements.txt#L1)):*
I feel like I'm missing something here?

---

*[tests/test_query_execution.py, line 32 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y1Or1L_A02k-u-wTf:-K7Y1Or1L_A02k-u-wTg:-490100116) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/tests/test_query_execution.py#L32)):*
Nice.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/13)*

**Comment by mtlynch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[bigsanity/query_execution.py, line 18 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7XyKIH_-8GXz4BEXgm:-K7Y2qV5yjxcK2Vvx_62:754515503) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L18)):*
The style guide specifies the name as `Error` unless I'm misunderstanding:

>Modules or packages should define their own domain-specific base exception class, which should inherit from the built-in Exception class. The base exception for a module should be called Error.

https://google.github.io/styleguide/pyguide.html?showone=Exceptions#Exceptions

---

*[bigsanity/query_execution.py, line 38 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y0XwjmvDrfAxw2A6B:-K7Y34H3RYZYqiWp2wxP:-2117477817) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L38)):*
Yeah the query will already have newlines. Is there reason to avoid them in exception messages?

---

*[test-requirements.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y-i3-3QAreamY0hMa:-K7Y3oGBevHpwFiO5J_r:-1440185147) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/test-requirements.txt#L1)):*
There's a `requirements.txt` that a user can use for `pip install -r` to get all the pre-reqs, then similarly a `test-requirements.txt` so the user can get all the pre-reqs for the test suite also. We use a similar pattern in Telescope. I added a small explanation to the README.

Also, now that you mention it,  I should add this to the Travis config. I think Travis gets mock automatically, but this will otherwise fail unexpectedly on Travis if we add other test pre-reqs.

---

*[tests/test_query_execution.py, line 32 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y1Or1L_A02k-u-wTf:-K7Y46jns-KKBJNacin0:-99050531) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/tests/test_query_execution.py#L32)):*
Yeah this was much less painful to mock out than I was expecting

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/13)*

**Comment by pboothe** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[bigsanity/query_execution.py, line 18 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7XyKIH_-8GXz4BEXgm:-K7Y5ZS_34oKTPRaa5Sl:677074204) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L18)):*
TIL.

---

*[bigsanity/query_execution.py, line 38 \[r1\]](https://reviewable.io:443/reviews/m-lab/bigsanity/13#-K7Y0XwjmvDrfAxw2A6B:-K7Y5aeMV45mVJdyOeXC:-860053917) ([raw file](https://github.com/m-lab/bigsanity/blob/b420ba9fc57f4cb6a7777bf92fb100b2d5631b7e/bigsanity/query_execution.py#L38)):*
Preformatting error messages has a tendency to break logging systems, or at least make their output less useful. So there's a soft preference for not having them if you have a choice. But since the newlines are already in the query, it's fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/13)*

**Pull request merged**
