### PR TITLE
Adding table name generator

### PR DESCRIPTION
**Pull request by mtlynch**
Adding a module to generate M-Lab BigQuery table names for given
projects or given time ranges.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/bigsanity/2)

### CODE REVIEW

**Comment by fernandalavalle** [comment]
Okay just for my understanding: the monthly fast tables and the project specific tables, how do they fit in together? Are the project specific tables still fast just a different view of the same data?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[bigsanity/table_names.py, line 139 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K51ZfRshbTHPvnO4xmQ:-K51ZfRshbTHPvnO4xmR:-2035590259) ([raw file](https://github.com/m-lab/bigsanity/blob/058d8eb3ac4eba8abe871d8a44bcd68e73ec9a6d/bigsanity/table_names.py#L139)):*
Kind of a detail, but if they're always going to be monthly we don't have to check each day if there's a new table name, right? At the least it would be every 27 days with the buffer?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-:-K51ZOY-UZte49yjHLrL:-11024970)*

**Comment by mtlynch** [comment]
Correct, it's all the same data sliced different ways (except legacy includes intermediate snapshots).

* legacy monthly: all projects, all snapshots, per month
* new monthly: all projects, last snapshots snapshots, per month
* per-project: single project, last snapshots, all time

Ideally, we wouldn't have the monthly tables at all, but I wanted to offer a way for users to migrate their existing BigQuery SQL with minimal effort and minimal risk. I want the project-specific tables to be the ones that we reference in all public documentation and examples, though.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[bigsanity/table_names.py, line 139 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K51ZfRshbTHPvnO4xmQ:-K52O6tKGsF-H29VCKSf:17953772) ([raw file](https://github.com/m-lab/bigsanity/blob/058d8eb3ac4eba8abe871d8a44bcd68e73ec9a6d/bigsanity/table_names.py#L139)):*
Yeah, good observation. This is not efficient.

There are alternatives like doing 27 day jumps but I find that hard to reason about to be confident that 27 is a safe number because time has a ton of weird edge cases.

The other thing I considered was rounding down to midnight on the 1st of the month, then incrementing 1 month forward but it felt like extra work for no real gain. It's a very performance-insensitive part of the code so going 30x slower than optimal doesn't really hurt us.

What do you think is a good tradeoff between simplicity and clean code? I added a comment explaining the current implementation, but I'm open to suggestions here for a better way of doing it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-:-K52M49hj8kgzZtUKt0I:-1650119527)*

**Comment by collina** [comment]
*[bigsanity/table_names.py, line 156 \[r3\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K52QnJHUOfPSRdvWh4e:-K52QnJHUOfPSRdvWh4f:-460572775) ([raw file](https://github.com/m-lab/bigsanity/blob/125ca84a0c0cefa1a2e68a84140b16a1b9c9a142/bigsanity/table_names.py#L156)):*
Oh my, this seems a bit cumbersome stylistically. Is there a better way to do it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2)*

**Comment by collina** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bigsanity/table_names.py, line 139 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K51ZfRshbTHPvnO4xmQ:-K52QEe3EBSsfmv0UzRg:-704461469) ([raw file](https://github.com/m-lab/bigsanity/blob/058d8eb3ac4eba8abe871d8a44bcd68e73ec9a6d/bigsanity/table_names.py#L139)):*
The current code seems cleaner, otherwise the alternative appears to be something like dateutil.rrule as with Telescope.
https://github.com/m-lab/telescope/blob/master/telescope/query.py#L200

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2)*

**Comment by mtlynch** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bigsanity/table_names.py, line 156 \[r3\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K52QnJHUOfPSRdvWh4e:-K52TN5nYNtW4loMdmoH:510763221) ([raw file](https://github.com/m-lab/bigsanity/blob/125ca84a0c0cefa1a2e68a84140b16a1b9c9a142/bigsanity/table_names.py#L156)):*
I generally see this as an accepted pseudo-switch in Python:

http://www.pydanny.com/why-doesnt-python-have-switch-case.html
http://stackoverflow.com/questions/11479816/what-is-the-python-equivalent-for-a-case-switch-statement

It doesn't strike me as that weird but I think I'm used to seeing it. Open to suggestions for alternatives.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2)*

**Comment by fernandalavalle** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bigsanity/table_names.py, line 139 \[r2\]](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-K51ZfRshbTHPvnO4xmQ:-K52XNFK68afP4DmEfxY:1245460677) ([raw file](https://github.com/m-lab/bigsanity/blob/058d8eb3ac4eba8abe871d8a44bcd68e73ec9a6d/bigsanity/table_names.py#L139)):*
yeah, I'm happy with this simple version if you're not sure 27 is safe. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2#-:-K52Xs5LE7FgZilF1sF-:676834233)*

**Comment by fernandalavalle** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/bigsanity/2)*

**Pull request merged**
